core/blockchain/difficulty.go, core/types/pow/blake2bd.go, core/types/pow/cuckaroo.go, core/types/pow/cuckatoo.go, core/types/pow/diff.go, core/types/pow/ipow.go, node/api.go, params/params_mainnet.go, params/params_mixnet.go, params/params_privnet.go, params/params_testnet.go, services/miner/cpuminer.go
- fix diff ajustment
- fix pow count stats
=> fix diff ajustment bug

core/blockchain/difficulty.go, core/json/blocktemplate.go, core/types/pow/blake2bd.go, core/types/pow/cuckaroo.go, core/types/pow/cuckatoo.go, core/types/pow/diff.go, core/types/pow/diff_test.go, core/types/pow/ipow.go, params/params_mainnet.go, params/params_mixnet.go, params/params_privnet.go, params/params_testnet.go, services/miner/api.go, services/miner/cpuminer.go, services/mining/newblocktemplate.go
- difficulty adjust by pow percent
- difficulty ajustment test code
- remove default same scale params,perfect calculation of scale value with edge bits,making difficulty directly related to edge bits
- add difficulty convert to target method
=> add difficulty test && optimize scale calculate

core/blockchain/validate.go, core/serialization/elements.go, core/types/block.go, core/types/pow/blake2bd.go, core/types/pow/cuckaroo.go, core/types/pow/cuckatoo.go, core/types/pow/cuckoo.go, core/types/pow/ipow.go, params/params_mixnet.go, params/params_testnet.go, services/miner/cpuminer.go
#126 
Abstract data and unified hash
=> uniform blockhash

core/types/pow/blake2bd.go, core/types/pow/cuckaroo.go, core/types/pow/cuckatoo.go, core/types/pow/cuckoo.go, core/types/pow/diff.go, core/types/pow/diff_test.go, core/types/pow/ipow.go, crypto/cuckoo/cuckatoo.go, crypto/cuckoo/cuckoo.go
format the code
- from 4 white space to tab
=> format go code

core/blockchain/difficulty.go, core/protocol/protocol.go, core/serialization/elements.go, core/types/block.go, core/types/pow/blake2bd.go, core/types/pow/diff.go, core/types/pow/diff_test.go, services/miner/cpuminer.go
#Fix Bug
- #137 
- fix block header bug(when the blake2bd block length less than the all header length). header length is 282. but blake2bd header is 113. when blake2bd block length is less than 282.then it will be a bug. fix all pow header is 282.
- fix difficulty ajustment
- fix difficulty compare
#143
=> fix bug about block header && fix difficuty ajust bug

core/blockchain/process.go
It will error when checkpoint open
=> fix bug about checkpoint verify

core/blockchain/difficulty.go, params/params.go
- Difficulty adjustment cycle error
=> fix bug about difficulty need adjustment count

qitmeerd.go, services/common/db.go
https://github.com/Qitmeer/qitmeer/issues/160
=> BUG:clean db fail for windows platform

core/blockchain/difficulty.go
Fix difficulty percent calculate base count
=> Fix difficulty percent calculate

core/serialization/elements.go, core/types/block.go, core/types/pow/blake2bd.go, core/types/pow/cuckoo.go, core/types/pow/ipow.go
Fix cuckoo block data 
- Contain the Proof Data
The miner must first calc cuckoo circle nonces ,then calculate hash
=> fix cuckoo block data 

.gitignore, crypto/cuckoo/siphash/siphash_other.go
fix compiling issue on arm architecture
=> support more platforms

core/blockdag/blockdag.go
https://github.com/Qitmeer/qitmeer/issues/190
=> BUG:error when miner submit block

core/blockchain/blockchain.go, core/blockdag/pantomblock.go
https://github.com/Qitmeer/qitmeer/issues/199
=> BUG:About data serialization of DAG

core/message/msgversion.go
it's only workaround of the version msg oversize error
the real fix should resolve the issue https://github.com/Qitmeer/qitmeer/issues/210
=> a hot-fix of issue 209

cmd/qx/README.md, cmd/qx/qx.go, qx/handle_difficulty.go
```bash
$ ./qx compact-to-uint64 34185984
$ echo 34185984 | ./qx compact-to-uint64
```
```bash
$ ./qx uint64-to-compact 2467
$ echo 2467 | ./qx uint64-to-compact
```
=> add qx difficulty tool

cmd/qx/README.md, cmd/qx/qx.go, qx/handle_difficulty.go
```bash
$ echo 34185984 | ./qx compact-to-uint64 | ./qx diff-to-gps -e 29 -t 15
$ ./qx diff-to-gps -e 24 -t 30 2745
```
=> convert hsahrate

cmd/qx/README.md, cmd/qx/qx.go, core/blockchain/validate.go, core/types/pow/cuckaroo.go, core/types/pow/cuckatoo.go, core/types/pow/diff.go, core/types/pow/diff_test.go, qx/handle_difficulty.go, services/miner/cpuminer.go, services/mining/newblocktemplate.go
```bash
$ echo 1863 | ./qx diff-to-gps -t 15 -e 24 | ./qx gps-to-diff -t 15 -e 24 -m 0
```
=> modify small graph and big graph difficulty

services/index/txindex.go
https://github.com/Qitmeer/qitmeer/issues/257
=> BUG:txindex missing issues

script/start.sh
1.  use home directory to avoid config file conflict
2. missing network parameter
=> fix script

core/json/blocktemplate.go, core/types/blocktemplate.go, core/types/pow/config.go, core/types/pow/cuckaroom.go, core/types/pow/ipow.go, crypto/cuckoo/cuckaroom.go, crypto/cuckoo/cuckaroom_test.go, crypto/cuckoo/siphash/siphash.go, go.mod, params/genesis.go, params/params_privnet.go, params/params_test.go, services/miner/api.go, services/mining/newblocktemplate.go
=> pow pack cuckaroom 29 

cmd/qx/qx.go, go.mod, qx/handle_difficulty.go, qx/qx_test.go
```bash
$ ./qx diff-to-target 471859199
$ 0x000000001fffff00000000000000000000000000000000000000000000000000
$ echo 0x000000001fffff00000000000000000000000000000000000000000000000000 | ./qx target-to-diff
$ 471859199
$ ./qx compact-to-hashrate 471859199
$ 34.35975475 GH/s
$ echo 34359754750 | ./qx hashrate-to-compact
$ 471859199
```
=> add hashrate convert qx cmd

cmd/qx/qx.go, core/blockchain/const.go, core/types/pow/diff.go, qx/handle_difficulty.go, qx/qx_test.go
```bash?linenums
$ ./qx compact-to-difficulty 471859199
$ 343597547
$ echo 471859199 | ./qx compact-to-difficulty  -mode hashrate
$ 343.597547 MH/s
$ ./qx difficulty-to-compact 343597547
$ 471859199
$ echo 343597547 | ./qx difficulty-to-compact
$ 471859199
$ ./qx compact-to-gps 36284416
$ 6.681034 GPS
$ echo 6.681034 | ./qx gps-to-compact
$ 36284416
```
=> add qx params

cmd/qx/qx.go, services/blkmgr/api.go
& fix `qx tx-decode` display bug.
=> add GetBlockByNum RPC to obsolete GetBlockByID RPC

core/blockchain/stxo.go, core/blockchain/utxo.go, core/blockchain/validate.go, core/blockdag/pantomblock.go
All nodes must clear the data and restart:  --cleanup
=> BUG:spent tx output is error

qx/handle_crypto.go
to fix https://github.com/Qitmeer/qitmeer-wallet/issues/50
=> extract EncodeWIF from EcPrivateKeyToWif

cmd/fastibd/config.go, cmd/fastibd/fastibd.go, cmd/fastibd/node.go, cmd/payledger/binode.go, cmd/payledger/danode.go, cmd/payledger/node.go, cmd/payledger/payledger.go, common/marshal/marshal.go, config/config.go, core/blockchain/accept.go, core/blockchain/blockchain.go, core/blockchain/blockindex.go, core/blockchain/blocknode.go, core/blockdag/blockdag.go, core/blockdag/blockdag_test.go, core/blockdag/phantom.go, core/blockdag/spectre.go, core/dbnamespace/dbnamespace.go, core/json/tx.go, ledger/ledger.go, script/cli.sh, services/blkmgr/api.go, services/blkmgr/blkmgr.go, services/common/load.go, services/index/indexmgr.go, services/index/invalidtx.go, services/index/txindex.go, services/tx/api.go
Fix https://github.com/Qitmeer/qitmeer/issues/344
=> Cache invalid tx;BUG:payledger utxo

core/blockdag/phantom.go
=> [Fix 355]isblue error

p2p/discover/v5_encoding.go
=> Compatible >=go1.16:remove use of shared hash instance for key derivation

README.md
https://github.com/Qitmeer/qitmeer/issues/444
=> [Resolve #444]FAQ of one synchronization issue

testutils/harness_test.go, testutils/utils.go, testutils/ws_test.go
=> fix test address not right

core/blockdag/phantom.go
User friendly solution for data exception:https://github.com/Qitmeer/qitmeer/issues/496
=> Optimize dag about data validity detection

cmd/qitmeerd/qitmeerd.go
=> ascii logo

core/address/address_test.go, core/blockchain/token/token_test.go, core/blockchain/validate_test.go, params/params_mixnet.go
fix the `mixnet` address prefix
=> 0.10 dev : fix the mixnet address prefix

Makefile
```golang
$ make dev
Build dev version : 0.10.3
Build build/dev/darwin/amd64/bin/qitmeer
Build build/dev/linux/amd64/bin/qitmeer
Build build/dev/windows/amd64/bin/qitmeer.exe
$ ./build/dev/darwin/amd64/bin/qitmeer --version
qitmeer version 0.10.3+dev-4a521d9 (Go version go1.16.6)
```
=> make : add dev target to Makefile

rpc/wsclient.go
c.serviceRequestSem.acquire() execute twice
=> fix bug about ws

rpc/scan.go
[https://github.com/Qitmeer/qitmeer-wallet/issues/136](url)
[ERROR] Stopping rescan for reorged block 8e26038085633938521ed3fff9a0b1b32ea528371b0a59b8d1581678d001393e (replaced by block b62a4d2807a0f59b48654eb9b83521c27a3977e86ce9b90d842ac6d8fa99416a) module=RPC
=> fix rescan stop
